# Generated by Django 5.0.7 on 2024-07-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('level_access', models.PositiveIntegerField(choices=[(0, 'Seller'), (1, 'SubSeller'), (10, 'Admin')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
