# Generated by Django 5.0.7 on 2024-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level_access',
            field=models.PositiveIntegerField(choices=[(0, 'employe'), (1, 'head'), (10, 'Admin')], default=0),
        ),
    ]
